# Generated by Django 5.0.7 on 2024-08-07 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('json_file', models.FileField(upload_to='assignment-files/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
